apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.port | quote }}
      targetPort: {{ .Values.app.port }}
      port: {{ .Values.app.port }}
  selector:
    service: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: NEXTAUTH_URL
              value: "https://{{ .Values.ingress.domain }}"
          image: {{ .Values.app.image }}
          resources:
            requests:
              memory: 100Mi
          name: frontend
          ports:
            - containerPort: {{ .Values.app.port }}
      restartPolicy: Always
      nodeSelector:
        node-type: stateless
      tolerations:
        - key: node-type
          operator: Equal
          value: stateless
          effect: NoSchedule
