apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: {{ .Values.app.port }}
